[#6] |Fixes the pre-commit hook to abort commit when tests fail| Pradipta/Rashmika

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -2,6 +2,10 @@
 
 set -e
 deno lint --fix
-deno test -A
 deno fmt --check
+deno test -A 
+if [$? -ne 0]; then
+  echo "Tests failed"
+  exit 1
+fi
 deno task test:coverage
